site_name: MC6 MKII Manual
sire_url: www.morningstarfx.com
theme: cinder
site_description: User manual for the Morningstar MC6 MKII
site_author: Morningstar Engineering
copyright: © 2018 MorningstarFX Pte Ltd
google_analytics: 
nav:
  - Home: index.md
  - User Guide:
    - Hardware I/Os: user-guide/hardware-overview.md
    - Main Config Menu: user-guide/main-config-menu.md
    - General Usage: user-guide/general-usage.md
    - Programming: user-guide/edit-mc6.md
    - Midi Editor: user-guide/midi-editor.md
  - Glossary:
    - Midi Types: glossary/midi-type-glossary.md
    - Actions: glossary/action-glossary.md
  - MIDI Implementation: midi-implementation.md
  - FAQ: FAQ.md
  - Help: help.md
plugins:
    - search
    - pdf-export