site_name: MC6 MKII Manual
sire_url: www.morningstarfx.com
theme: cinder
site_description: User manual for the Morningstar MC6 MKII
site_author: Morningstar Engineering
copyright: © 2018 MorningstarFX Pte Ltd
google_analytics: 
nav:
  - Home: 01-main.md
  - User Guide:
    - Hardware I/Os: 02-user-guide/hardware-overview.md
    - Main Config Menu: user-guide/03-main-config-menu.md
    - General Usage: user-guide/04-general-usage.md
    - Programming: user-guide/05-edit-mc6.md
    - Midi Editor: user-guide/06-midi-editor.md
  - Glossary:
    - Midi Types: glossary/07-midi-type-glossary.md
    - Actions: glossary/08-action-glossary.md
  - MIDI Implementation: 09-midi-implementation.md
  - FAQ: FAQ.md
  - Help: help.md
plugins:
    - search
    - pdf-export